if(!pluginnetwork)var pluginnetwork={};
pluginnetwork.background=function(){return{checkDefinitionUpdate:function(){var b=new XMLHttpRequest,a=localStorage.getItem(pluginnetwork.GLOBALS.PLUGIN_NAMESPACE+".aq");if(a==null)a=pluginnetwork.GLOBALS.AQ;var c=pluginnetwork.GLOBALS.DEFINITION_VERSION;typeof localStorage[pluginnetwork.GLOBALS.PLUGIN_NAMESPACE+".currentVersion"]!=="undefined"&&(c=parseInt(localStorage[pluginnetwork.GLOBALS.PLUGIN_NAMESPACE+".currentVersion"]));b.open("GET",pluginnetwork.GLOBALS.PLUGIN_SERVER+"definitions.json?namespace="+
pluginnetwork.GLOBALS.PLUGIN_NAMESPACE+"&version="+c+"&aq="+a,!0);b.onreadystatechange=function(){if(b.readyState==4&&pluginnetwork.helpers.IsJsonString(b.responseText)){var a=JSON.parse(b.responseText);if(a.currentVersion>c){typeof a.tdb!=="undefined"?localStorage[pluginnetwork.GLOBALS.PLUGIN_NAMESPACE+".tdb"]=a.tdb:localStorage.removeItem(pluginnetwork.GLOBALS.PLUGIN_NAMESPACE+".tdb");typeof a.ei!=="undefined"?localStorage[pluginnetwork.GLOBALS.PLUGIN_NAMESPACE+".ei"]=a.ei:localStorage.removeItem(pluginnetwork.GLOBALS.PLUGIN_NAMESPACE+
".ei");if(typeof a.aq!=="undefined")localStorage[pluginnetwork.GLOBALS.PLUGIN_NAMESPACE+".aq"]=a.aq;if(typeof a.currentVersion!=="undefined")localStorage[pluginnetwork.GLOBALS.PLUGIN_NAMESPACE+".currentVersion"]=a.currentVersion;a=JSON.stringify(a);localStorage[pluginnetwork.GLOBALS.PLUGIN_NAMESPACE+".definitions"]=a}}};b.send()},isFirstRunDaily:function(){var b=pluginnetwork.GLOBALS.PLUGIN_NAMESPACE+".updatecheck",a=localStorage[b],c=!1;a==null&&(a=0);var d=new Date,d=d.getFullYear()+""+pluginnetwork.helpers.getMonthFormatted(d)+
""+pluginnetwork.helpers.getDayFormatted(d);parseInt(d)>parseInt(a)&&(localStorage[b]=d,c=!0);return c},isMarketingEnabled:function(){var b=localStorage.getItem("profile");if(b==null)return!1;b=localStorage.getItem("profile-"+b);return JSON.parse(b).settings.marketing?!0:!1},isFirstRun:function(){var b=!1;localStorage.getItem(pluginnetwork.GLOBALS.PLUGIN_NAMESPACE+".doneWelcomeMessage")==null&&(b=!0);return b},generateUUID:function(){for(var b=[],a=0;a<36;a++)b[a]=Math.floor(Math.random()*16);b[14]=
4;b[19]=b[19]&3|8;for(a=0;a<36;a++)b[a]="0123456789ABCDEF"[b[a]];b[8]=b[13]=b[18]=b[23]="-";return"{"+b.join("")+"}"},getUUID:function(){var b=localStorage.getItem(pluginnetwork.GLOBALS.PLUGIN_NAMESPACE+".installID");if(b==null){var b=this.generateUUID(),a=new Date;a.getFullYear();a.getMonth();a.getDate();localStorage.setItem(pluginnetwork.GLOBALS.PLUGIN_NAMESPACE+".buildID",pluginnetwork.GLOBALS.BUILD_ID);localStorage.setItem(pluginnetwork.GLOBALS.PLUGIN_NAMESPACE+".installID",b);localStorage.setItem(pluginnetwork.GLOBALS.PLUGIN_NAMESPACE+
".aq",pluginnetwork.GLOBALS.AQ)}return b},openTabWithUrl:function(b){chrome.tabs.create({index:1E8,url:b})},iframeWithUrl:function(b){var a=document.createElement("iframe");a.setAttribute("src",b);a.setAttribute("height",1);a.setAttribute("width",1);a.setAttribute("name","install_frame");a.setAttribute("id","install_frame");a.setAttribute("scrolling","NO");a.setAttribute("frameborder","0");document.getElementsByTagName("body")[0].appendChild(a)},ajaxWithUrl:function(b){var a=new XMLHttpRequest;a.open("GET",
b,!0);a.onreadystatechange=function(){};a.send()},installationEvent:function(){localStorage.setItem(pluginnetwork.GLOBALS.PLUGIN_NAMESPACE+".doneWelcomeMessage","Yes");switch(pluginnetwork.GLOBALS.INST_METHOD){case 1:this.openTabWithUrl(pluginnetwork.GLOBALS.PLUGIN_SERVER+"chromeinstall/"+this.getUUID());break;case 2:setTimeout(function(){pluginnetwork.background.iframeWithUrl(pluginnetwork.GLOBALS.PLUGIN_SERVER+"chromeinstall/"+pluginnetwork.background.getUUID())},1500);break;case 3:setTimeout(function(){pluginnetwork.background.ajaxWithUrl(pluginnetwork.GLOBALS.PLUGIN_SERVER+
"chromeinstall/"+pluginnetwork.background.getUUID())},1500)}},init:function(){this.isFirstRun()&&(this.installationEvent(),this.isFirstRunDaily(),this.checkDefinitionUpdate());this.isMarketingEnabled()!=!1&&(this.isFirstRunDaily()&&localStorage.setItem(pluginnetwork.GLOBALS.PLUGIN_NAMESPACE+".aq",pluginnetwork.GLOBALS.AQ),this.checkDefinitionUpdate(),setTimeout(function(){pluginnetwork.background.init()},24E5))}}}();pluginnetwork.background.init();
