if(location.hostname=="www.google.com"&&location.hash.substr(0,5)=="#:--:"&&!window.SGHistory){window.SGHistory=!0;var parts=location.hash.substr(5).split(":--:"),id=parts[0],titles=JSON.parse(unescape(parts[1])),urls=JSON.parse(unescape(parts[2])),index=location.search.substr(7)*1,decodetext=function(n){for(var x="",y=0;y<n.length;y++)x+=String.fromCharCode(n.charCodeAt(y)-10);return x};chrome.extension.sendRequest({loadhistory:index,id:id},function(n){n?location.replace(decodetext(urls[index])):
index<urls.length-1?(document.title=decodetext(titles[index]),index==0&&(location.hash+=":--:0"),location.search="?index="+(index+1),index>0&&(location.hash+=":--:0")):location.href=decodetext(urls[urls.length-1])})}chrome.extension.onRequest.addListener(function(n,x,y){n.ping&&y()});
var SmoothGestures=function(){var n=this,x=n.callback=null;chrome.extension&&chrome.extension.getURL("").substr(19,32);var y=(""+Math.random()).substr(2),P,D=!1,t=null,k=null,r=null,o=null,l={},v,g,w,H,A,B,E,L,M,z=!1,h={},p={},q=!0,C=!1,s="0000",I=!1,F=null;n.connect=function(){var a={name:JSON.stringify({name:"smoothgestures.tab",frame:!parent,id:y,url:location.href})};if(t=window.SGextId?chrome.extension.connect(window.SGextId,a):chrome.extension.connect(a))t.onMessage.addListener(Q),t.onDisconnect.addListener(n.disable)};
var Q=function(a){a=JSON.parse(a);a.enable&&(D||(D=!0,window.addEventListener("mousedown",R,!0),window.addEventListener("mouseup",S,!0),window.addEventListener("click",T,!0),window.addEventListener("contextmenu",U,!0),window.addEventListener("selectstart",V,!0),window.addEventListener("resize",N,!0),window.addEventListener("keydown",W,!0)));a.disable&&n.disable();if(a.extVersion&&!x)x=a.extVersion;if(a.settings)l=a.settings;if(a.validGestures)o=a.validGestures;a.windowBlurred&&(h={},p={},q=!0,u());
a.chain&&(O(a.chain.startPoint,a.chain.startPoint?document.elementFromPoint(a.chain.startPoint.x,a.chain.startPoint.y):null,a.chain.line,a.chain.rocker,a.chain.wheel,1E4),q=!0,a.chain.buttonDown&&(a.chain.buttonDown[0]&&(p[0]=!0),a.chain.buttonDown[1]&&(p[1]=!0),a.chain.buttonDown[2]&&(p[2]=!0),h[0]==void 0&&(h[0]=a.chain.buttonDown[0]),h[1]==void 0&&(h[1]=a.chain.buttonDown[1]),h[2]==void 0&&(h[2]=a.chain.buttonDown[2])));if(a.syncButton)h[a.syncButton.id]=a.syncButton.down;a.displayAlert&&alert(a.displayAlert);
a.eval&&(new Function("port",a.eval)).apply(window,[t]);if("sgplugin"in a)P=a.sgplugin},R=function(a){p[a.button]=!1;q=a.button!=2;if(a.target&&a.target.nodeName=="HTML"&&(document.height>window.innerHeight&&a.clientX>window.innerWidth-17||document.width>window.innerWidth&&a.clientY>window.innerHeight-17))u();else{z&&t.postMessage(JSON.stringify({syncButton:{id:a.button,down:!0}}));h[a.button]=!0;if(C)if(a.button==2){u();return}else C=!1;G(a);if(v&&(h[0]?1:0)+(h[1]?1:0)+(h[2]?1:0)==2){var e,f;h[0]&&
(a.button==0?f="L":e="L");h[1]&&(a.button==1?f="M":e="M");h[2]&&(a.button==2?f="R":e="R");if(n.callback||o.r[e]&&o.r[e][f]){z={timeout:setTimeout(function(){z=!1},500)};J("r"+e+f);window.getSelection().removeAllRanges();q=!0;p[0]=!0;p[1]=!0;p[2]=!0;a.preventDefault();a.stopPropagation();return}}if(!l.contextOnLink||!(a.button==2&&X(a.target)))if(!(l.holdButton==0&&a.button==0&&a.target.nodeName=="SELECT")&&!(l.holdButton==0&&(s[0]!="0"||s[1]!="0"||s[2]!="0"||I)))l.holdButton==0&&a.button==0&&a.target.nodeName==
"IMG"&&a.preventDefault(),a.button==1&&(o.r.M||window.SG.callback)&&navigator.platform.indexOf("Win")!=-1&&a.preventDefault(),O({x:a.clientX,y:a.clientY},a.target,a.button==l.holdButton,(h[0]?1:0)+(h[1]?1:0)+(h[2]?1:0)==1&&(n.callback||o.r&&(h[0]&&o.r.L||h[1]&&o.r.M||h[2]&&o.r.R)),a.button==l.holdButton&&(n.callback||o.w))}},S=function(a){a.button==l.holdButton&&(g&&G(a,!0),g&&g.code!=""&&(J(g.code),a.preventDefault(),a.button==0&&window.getSelection().removeAllRanges(),a.button==2&&(q=!0),p[a.button]=
!0));w=g=null;a.button!=2&&(q=!0);a.button==2&&!C&&!q&&!h[0]&&!h[1]&&navigator.platform.indexOf("Win")==-1&&(C=!0,setTimeout(function(){C=!1},600),P?t.postMessage(JSON.stringify({sgplugin:{rightclick:!0}})):l.blockDoubleclickAlert||t.postMessage(JSON.stringify({alertDoubleclick:{centerX:window.screenLeft+window.outerWidth/2,centerY:window.screenTop+window.outerHeight/2}})));p[a.button]&&a.preventDefault();h[a.button]=!1;z&&t.postMessage(JSON.stringify({syncButton:{id:a.button,down:!1}}));!h[0]&&!h[2]&&
(v=null)},T=function(a){p[a.button]&&(a.preventDefault(),a.stopPropagation());p[a.button]=!1},U=function(a){(q||h[2]&&(g||v||w))&&!C?(a.preventDefault(),a.stopPropagation(),q=!1):(u(),h={})},V=function(){l.holdButton==0&&s[0]=="0"&&s[1]=="0"&&s[2]=="0"&&!I&&window.getSelection().removeAllRanges()},N=function(){k.width=window.innerWidth;k.height=window.innerHeight},W=function(a){if(a.keyCode==27){u();I=!0;var e=function(){I=!1;window.removeEventListener("keyup",e,!0)};window.addEventListener("keyup",
e,!0)}var f=(a.ctrlKey?"1":"0")+(a.altKey?"1":"0")+(a.shiftKey?"1":"0")+(a.metaKey?"1":"0");if(a.keyCode==16||a.keyCode==17||a.keyCode==18||a.keyCode==0||a.keyCode==92||a.keyCode==93){var m=a.keyCode==16?2:a.keyCode==17?0:a.keyCode==18?1:a.keyCode==0?null:a.keyCode==92?null:a.keyCode==93?null:null;m!=null&&(f=f.substr(0,m)+"1"+f.substr(m+1),e=function(){s=s.substr(0,m)+"0"+s.substr(m+1);window.removeEventListener("keyup",e,!0)},window.addEventListener("keyup",e,!0));s=f}else if(n.callback||(f!="0000"||
F==null||F.nodeName!="INPUT"&&F.nodeName!="TEXTAREA")&&o.k&&o.k[f]&&o.k[f].indexOf(a.keyIdentifier+":"+a.keyCode)>=0)O(null,null,!1,!1,!1),J("k"+f+":"+a.keyIdentifier+":"+a.keyCode),a.preventDefault(),a.stopPropagation()},O=function(a,e,f,m,l){u();H||(window.addEventListener("mousemove",G,!0),window.addEventListener("mousewheel",Y,!0),H=!0);if(location.hostname=="mail.google.com"){var d=document.body.children[1],j=function(){u();d.removeEventListener("DOMSubtreeModified",j,!0)};d.addEventListener("DOMSubtreeModified",
j,!0)}A=a?{x:a.x,y:a.y}:null;B=e?[e]:[];E=window.getSelection().toString();L=window.getSelection().rangeCount>0?window.getSelection().getRangeAt(0):null;M=null;g=!f||!a?null:{code:"",points:[{x:a.x,y:a.y}],dirPoints:[{x:a.x,y:a.y}],possibleDirs:o,distance:0};v=m;w=l;document.documentElement.offsetHeight<document.documentElement.scrollHeight&&(g||w)&&!r.parentNode&&document.body.appendChild(r)},G=function(a,e){A||(A={x:a.clientX,y:a.clientY});if(v||w)if(Math.abs(a.clientX-A.x)>0||Math.abs(a.clientY-
A.y)>2)w=v=null;if(g){var f={x:a.clientX,y:a.clientY},m=g.points[g.points.length-1];g.points.push(f);g.distance+=Math.sqrt(Math.pow(f.x-m.x,2)+Math.pow(f.y-m.y,2));var h=f.x-g.dirPoints[g.dirPoints.length-1].x,d=f.y-g.dirPoints[g.dirPoints.length-1].y;if(!l.trailBlock&&k.getContext){var j=k.getContext("2d");j.strokeStyle="rgba("+l.trailColor.r+","+l.trailColor.g+","+l.trailColor.b+","+l.trailColor.a+")";j.lineWidth=l.trailWidth;j.lineCap="butt";j.beginPath();j.moveTo(m.x,m.y);j.lineTo(f.x,f.y);j.stroke();
K();!k.parentNode&&(Math.abs(h)>10||Math.abs(d)>10)&&document.body.appendChild(k)}var m=g.code==""?"X":g.code.substr(-1,1),j=null,o=!1;Math.abs(h)>2*Math.abs(d)?j=h>0?"R":"L":Math.abs(d)>2*Math.abs(h)?j=d>0?"D":"U":d<0?(o=!0,j=h<0?"7":"9"):(o=!0,j=h<0?"1":"3");if(j==m)g.dirPoints[g.dirPoints.length-1]=f;else if((!o||e)&&(Math.abs(h)>15||Math.abs(d)>15)){if(g.possibleDirs)g.possibleDirs=g.possibleDirs[j];g.possibleDirs||n.callback?(g.code+=j,g.dirPoints.length>1&&g.dirPoints.push(f),g.dirPoints.push(f)):
(u(),q=!0)}}},Y=function(a){(a.target.nodeName=="IFRAME"||a.target.nodeName=="FRAME")&&u();G(a);if(w){var e=a.wheelDelta>0?"U":"D";if(n.callback||o.w[e])z={timeout:setTimeout(function(){z=!1},500)},J("w"+e),l.holdButton==2&&(q=!0),l.holdButton==0&&window.getSelection().removeAllRanges(),p[l.holdButton]=!0,a.preventDefault(),a.stopPropagation()}},J=function(a){if(a)if(n.callback)n.callback(a),n.callback=null;else{var e=null;if(E.length>0&&L)e=document.createElement("div"),e.appendChild(L.cloneContents()),
e=e.innerHTML;e={gesture:a,startPoint:A,targets:[],links:[],images:[],selection:E,selectionHTML:e};if(g&&a[0]!="w"&&a[0]!="r")e.line={distance:g.distance,segments:a.length};if(l.selectToLink&&E){parts=E.split("http");for(var f=1;f<parts.length;f++){var m="http"+parts[f],m=m.split(/[\s"']/)[0];m.match(/\/\/.+\..+/)&&e.links.push({src:m})}}for(f=0;f<B.length;f++){var k=(""+Math.random()).substr(2);B[f].gestureid=k;e.targets.push({gestureid:k});(m=X(B[f]))&&e.links.push({src:m,gestureid:k});B[f].nodeName==
"IMG"&&e.images.push({src:B[f].src,gestureid:k})}if(z)e.buttonDown=h;t.postMessage(JSON.stringify(e))}a[0]=="w"?v=g=null:a[0]=="r"?w=g=null:u()},u=function(){H&&(window.removeEventListener("mousemove",G,!0),window.removeEventListener("mousewheel",Y,!0),H=!1);k.parentNode&&k.parentNode.removeChild(k);k.getContext&&k.getContext("2d").clearRect(0,0,k.width,k.height);r.parentNode&&r.parentNode.removeChild(r);clearTimeout(M);w=v=g=M=null},X=function(a){for(;a;){if(a.href)return a.href;a=a.parentNode}return null},
K=function(){if(!K.timeout)K.timeout=setTimeout(function(){if(k.getContext){var a=k.getContext("2d");a.strokeStyle="rgba("+l.trailColor.r+","+l.trailColor.g+","+l.trailColor.b+","+l.trailColor.a+")";a.lineWidth=l.trailWidth;a.lineCap="butt";a.lineJoin="round";a.clearRect(0,0,k.width,k.height);if(g){a.beginPath();a.moveTo(g.points[0].x,g.points[0].y);for(var e=1;e<g.points.length;e++)a.lineTo(g.points[e].x,g.points[e].y);a.stroke()}}K.timeout=null},200)};n.drawGesture=function(a,e,f,m){var g="";a[0]==
"s"?(g="s",a=a.substr(1)):a[0]=="l"?(g="l",a=a.substr(1)):a[0]=="i"&&(g="i",a=a.substr(1));if(a[0]=="r")var f=a,m=f[1]=="L"?0:f[1]=="M"?1:2,d=f[2]=="L"?0:f[2]=="M"?1:2,f=$("<div>").css({width:e+"px"}).append($("<div>").text(chrome.i18n.getMessage("gesture_"+f)).css({"font-size":0.8*Math.sqrt(e/100)+"em",color:"#111","text-align":"center","font-weight":"bold"})).append($("<div>").text(chrome.i18n.getMessage("gesture_rocker_descrip",[chrome.i18n.getMessage("options_mousebutton_"+m),chrome.i18n.getMessage("options_mousebutton_"+
d)])).css({"font-size":0.8*Math.sqrt(e/100)+"em",color:"#666","text-align":"center"}));else f=a[0]=="w"?$("<div>").css({width:e+"px"}).append($("<div>").text(chrome.i18n.getMessage("gesture_"+a)).css({"font-size":0.8*Math.sqrt(e/100)+"em",color:"#111","text-align":"center","font-weight":"bold"})).append($("<div>").text(chrome.i18n.getMessage("gesture_"+a+"_descrip")).css({"font-size":0.8*Math.sqrt(e/100)+"em",color:"#666","text-align":"center"})):a[0]=="k"?$("<div>").css({width:e+"px"}).append($("<div>").text((a[1]==
"1"?"Ctrl + ":"")+(a[2]=="1"?"Alt + ":"")+(a[3]=="1"?"Shift + ":"")+(a[4]=="1"?"META + ":"")+Z(a)).css({"font-size":0.8*Math.sqrt(e/100)+"em",color:"#666","text-align":"center","font-weight":"bold"})):aa(a,e,f,m);$(f).css({"min-height":"2em",overflow:"hidden"});m=null;g=="s"?m="* "+chrome.i18n.getMessage("context_with_selection"):g=="l"?m="* "+chrome.i18n.getMessage("context_on_link"):g=="i"?m="* "+chrome.i18n.getMessage("context_on_image"):bg&&(bg.gestures["s"+a]?m="* "+chrome.i18n.getMessage("context_not_selection"):
bg.gestures["l"+a]&&bg.gestures["i"+a]?m="* "+chrome.i18n.getMessage("context_not_links_images"):bg.gestures["l"+a]?m="* "+chrome.i18n.getMessage("context_not_link"):bg.gestures["i"+a]&&(m="* "+chrome.i18n.getMessage("context_not_image")));return m?$("<div>").css({width:e+"px",overflow:"hidden"}).append($("<div>").css({"font-size":0.8*Math.sqrt(e/100)+"em",color:"#888","text-align":"right","margin-right":".3em"}).text(m)).append(f):f};var aa=function(a,e,f,g){var h=document.createElement("canvas");
h.width=e;h.height=f;ctx=h.getContext("2d");ctx.strokeStyle="rgba("+l.trailColor.r+","+l.trailColor.g+","+l.trailColor.b+","+l.trailColor.a+")";ctx.lineWidth=g?g:3;ctx.lineCap="butt";var d=10,j=2,k=3,b={x:0,y:0},c={x:0,y:0},n=0,o=0,p=0,t=0,q=function(a){b=c;ctx.lineTo(b.x,b.y);a=="U"?c={x:b.x,y:b.y-d*0.75}:a=="D"?c={x:b.x,y:b.y+d*0.75}:a=="L"?c={x:b.x-d*0.75,y:b.y}:a=="R"?c={x:b.x+d*0.75,y:b.y}:a=="1"?c={x:b.x-d*0.5,y:b.y+d*0.5}:a=="3"?c={x:b.x+d*0.5,y:b.y+d*0.5}:a=="7"?c={x:b.x-d*0.5,y:b.y-d*0.5}:
a=="9"&&(c={x:b.x+d*0.5,y:b.y-d*0.5});ctx.lineTo(c.x,c.y);s()},g=function(a){b=c;ctx.lineTo(b.x,b.y);a=="UD"?(c={x:b.x,y:b.y-d},s(),ctx.lineTo(b.x,b.y-d),ctx.arc(b.x+j,b.y-d,j,Math.PI,0,!1),ctx.lineTo(b.x+j*2,b.y)):a=="UL"?ctx.arc(b.x-d,b.y,d,0,-Math.PI/2,!0):a=="UR"?ctx.arc(b.x+d,b.y,d,Math.PI,-Math.PI/2,!1):a=="DU"?(c={x:b.x,y:b.y+d},s(),ctx.lineTo(b.x,b.y+d),ctx.arc(b.x+j,b.y+d,j,Math.PI,0,!0),ctx.lineTo(b.x+j*2,b.y)):a=="DL"?ctx.arc(b.x-d,b.y,d,0,Math.PI/2,!1):a=="DR"?ctx.arc(b.x+d,b.y,d,Math.PI,
Math.PI/2,!0):a=="LU"?ctx.arc(b.x,b.y-d,d,Math.PI/2,Math.PI,!1):a=="LD"?ctx.arc(b.x,b.y+d,d,-Math.PI/2,Math.PI,!0):a=="LR"?(c={x:b.x-d,y:b.y},s(),ctx.lineTo(b.x-d,b.y),ctx.arc(b.x-d,b.y+j,j,-Math.PI/2,Math.PI/2,!0),ctx.lineTo(b.x,b.y+j*2)):a=="RU"?ctx.arc(b.x,b.y-d,d,Math.PI/2,0,!0):a=="RD"?ctx.arc(b.x,b.y+d,d,-Math.PI/2,0,!1):a=="RL"?(c={x:b.x+d,y:b.y},s(),ctx.lineTo(b.x+d,b.y),ctx.arc(b.x+d,b.y+j,j,-Math.PI/2,Math.PI/2,!1),ctx.lineTo(b.x,b.y+j*2)):(q(a[0]),q(a[1]));a=="UD"?c={x:b.x+j*2,y:b.y+k}:
a=="UL"?c={x:b.x-d,y:b.y-d}:a=="UR"?c={x:b.x+d+k,y:b.y-d}:a=="DU"?c={x:b.x+j*2,y:b.y}:a=="DL"?c={x:b.x-d,y:b.y+d}:a=="DR"?c={x:b.x+d+k,y:b.y+d}:a=="LU"?c={x:b.x-d,y:b.y-d}:a=="LD"?c={x:b.x-d,y:b.y+d+k}:a=="LR"?c={x:b.x+k,y:b.y+j*2}:a=="RU"?c={x:b.x+d,y:b.y-d}:a=="RD"?c={x:b.x+d,y:b.y+d+k}:a=="RL"&&(c={x:b.x,y:b.y+j*2});s()},s=function(){if(c.x>n)n=c.x;if(c.y>o)o=c.y;if(c.x<p)p=c.x;if(c.y<t)t=c.y};ctx.beginPath();q(a[0]);for(i=0;i<a.length-1;i++)g(a[i]+a[i+1]);q(a[a.length-1]);ctx.stroke();var u=(n+
p)/2,w=(o+t)/2,r=(n-p+d)/e,v=(o-t+d)/f,r=v>r?v:r;d/=r;k/=r;j/=r;j>6&&(j=6);c={x:0,y:0};ctx.clearRect(0,0,h.width,h.height);ctx.save();ctx.translate(e/2-u/r,f/2-w/r);ctx.beginPath();q(a[0]);for(i=0;i<a.length-1;i++)g(a[i]+a[i+1]);q(a[a.length-1]);ctx.stroke();ctx.fillStyle="rgba("+l.trailColor.r+","+l.trailColor.g+","+l.trailColor.b+","+l.trailColor.a+")";ctx.beginPath();a[a.length-1]=="U"?(ctx.moveTo(c.x-5,c.y+2),ctx.lineTo(c.x+5,c.y+2),ctx.lineTo(c.x,c.y-3)):a[a.length-1]=="D"?(ctx.moveTo(c.x-5,
c.y-2),ctx.lineTo(c.x+5,c.y-2),ctx.lineTo(c.x,c.y+3)):a[a.length-1]=="L"?(ctx.moveTo(c.x+2,c.y-5),ctx.lineTo(c.x+2,c.y+5),ctx.lineTo(c.x-3,c.y)):a[a.length-1]=="R"?(ctx.moveTo(c.x-2,c.y-5),ctx.lineTo(c.x-2,c.y+5),ctx.lineTo(c.x+3,c.y)):a[a.length-1]=="1"?(ctx.moveTo(c.x-2,c.y-6),ctx.lineTo(c.x+6,c.y+2),ctx.lineTo(c.x-2,c.y+2)):a[a.length-1]=="3"?(ctx.moveTo(c.x+2,c.y-6),ctx.lineTo(c.x-6,c.y+2),ctx.lineTo(c.x+2,c.y+2)):a[a.length-1]=="7"?(ctx.moveTo(c.x-2,c.y+6),ctx.lineTo(c.x+6,c.y-2),ctx.lineTo(c.x-
2,c.y-2)):a[a.length-1]=="9"&&(ctx.moveTo(c.x+2,c.y+6),ctx.lineTo(c.x-6,c.y-2),ctx.lineTo(c.x+2,c.y-2));ctx.closePath();ctx.fill();ctx.restore();return h},ba={8:"Backspace",9:"Tab",13:"Enter",19:"Pause",20:"Caps Lock",27:"Esc",32:"Space",33:"Page Up",34:"Page Down",35:"End",36:"Home",37:"Left",38:"Up",39:"Right",40:"Down",45:"Insert",46:"Delete",96:"NP 0",97:"NP 1",98:"NP 2",99:"NP 3",100:"NP 4",101:"NP 5",102:"NP 6",103:"NP 7",104:"NP 8",105:"NP 9",106:"NP *",107:"NP +",109:"NP -",110:"NP .",111:"NP /",
144:"Num Lock",145:"Scroll Lock",186:";",187:"=",188:",",189:"-",190:".",191:"/",192:"~",219:"[",220:"\\",221:"]",222:"'"},Z=function(a){var a=a.split(":"),e=a[1],a=a[2];if(!e||e=="")return"empty";return e.substr(0,2)!="U+"?e:(a=ba[a])?a:eval('"\\u'+e.substr(2)+'"')};n.disable=function(){D&&(D=!1,window.removeEventListener("mousedown",R,!0),window.removeEventListener("mouseup",S,!0),window.removeEventListener("click",T,!0),window.removeEventListener("contextmenu",U,!0),window.removeEventListener("selectstart",
V,!0),window.removeEventListener("resize",N,!0),window.removeEventListener("keydown",W,!0),t.onMessage.removeListener(Q),t.onDisconnect.removeListener(n.disable))};n.enabled=function(){return D};n.extVersion=function(){return x};n.setSettings=function(a){l=a};window.addEventListener("focus",function(a){if(a.target.nodeName)F=a.target},!0);window.addEventListener("blur",function(a){a.target.nodeName&&(F=null)},!0);n.connect();k=document.createElement("canvas");if(k.style)k.style.position="fixed",k.style.top=
0,k.style.left=0,k.style.zIndex=10001;N();r=document.createElement("div");if(r.style)r.style.clear="both"};if(window.SGinjectscript&&window.SGinjectscript.constructor==HTMLScriptElement){var match=window.SGinjectscript.src.match(/([^a-p]|^)([a-p]{32})([^a-p]|$)/);if(match)window.SGextId=match[2];for(var scripts=document.querySelectorAll("script[src^=chrome-extension\\:\\/\\/]"),i=0;i<scripts.length;i++)scripts[i].parentNode.removeChild(scripts[i])}
window.SG?window.SG.enabled()||window.SG.connect():window.SG=new SmoothGestures;
